apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
spec:
  storageClassName: d17storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nmt/local"